### PR TITLE
chore(package): update find-node-modules to version 1.0.4

### LINKED ISSUE #374: vulnerable dependencies
- [npm:minimatch:20160620](https://snyk.io/vuln/npm:minimatch:20160620)

### PR DESCRIPTION
**Pull request by beeman**
This PR fixes a vulnerability with one of the dependencies of the `find-node-modules` package.

Fixes #374

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm, any idea why the build is failing?

**Comment by beeman** [comment]
Hi @LinusU , I don't have a clue. The tests run fine locally, both on master and this branch.

Maybe you can try to clear the cache in travis/appveyor? Looking at the open GreenKeeper PR's it looks like more tests are failing, but with different errors.

**Comment by jimthedev** [comment]
I need to merge master back into this so I'm merging into a different branch for now then will merge it into master. Thanks for the PR!

**Comment by jimthedev** [comment]
This is blocked by master. I merged #328 but unfortunately it is without tests so we need to fix that before we can complete this.

**Comment by jimthedev** [comment]
All merged!

**Comment by beeman** [comment]
@jimthedev awesome work on this project over the last week! Thanks a lot for maintaining it!

**Comment by jimthedev** [comment]
My pleasure and thank you for the kind words. I can't always get to all the issues right now, but eventually I'll get to them 😃

**Pull request merged**
