### PR TITLE
Recreate the commitizen logo in png & svg format

### PR DESCRIPTION
**Pull request by bromso**

### CODE REVIEW

**Comment by LinusU** [comment]
Awesome!

What is the use case for adding so many different sizes of the same image? Binary files are not great to put in Git because every version of the file gets stored forever and needs to be downloaded every time you `git clone`. How about keeping just the SVG files in the repository?

**Comment by dmwelch** [comment]
@bromso I narrowed down the generated sizes according to some very hasty online research.  I added 16x16 for the VSCode icon use case, then: 48, 96, 256, 512, 1024.  Adding more sizes is trivial, (see line 24 in `generate.sh`) but I'd rather have more information on use cases.

@LinusU I wanted to set up the Azure pipeline to generate them as build artifacts but not sure if I did that correctly (still learning this tech stack).  I avoided using `svgexport` and went with Python's `cairosvg` because I don't think the containers on Azure have browsers and testing on Docker locally demonstrated that `svgexport` requires the browser to render the PNG files.

**Comment by bromso** [comment]
It all sounds good to me. As long as you guys are happy, I'm happy! 😄

**Review by LinusU — APPROVED** [review]
Neat! 👍

**Pull request merged**
