### PR TITLE
doc: highlight pre-requisties and bubble up related sections 

### LINKED ISSUE #558: git cz just opens the local editor
git cz is broken for me.

I wanted to get started but it does not work.

I'm using Windows WSL (ubuntu shell on windows) together with zsh.

This is my gitconfig:

```
[alias]
        l = log --graph --color --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --
        ls = ls-files
        st = status
        amend = commit --amend
        amendn = ammend --no-edit
        diffs = diff --staged
        ch = checkout
        f = fetch
        p = push
        c = commit
        a = add -p
        r = reset -p
        aliases = !git config -l | grep alias | cut -c 7-
        whois = !sh -c 'git log -i -1 --pretty=\"format:%an <%ae>\n\" --author=\"$1\"' -
[diff]
        tool = meld
[push]
        default = simple
[core]
        autocrlf = input
[branch]
        autosetuprebase = always
```

Even with my gitconfig removed, I get the following: 

cz

Is there a known bug?

### PR DESCRIPTION
**Pull request by mrchief**
Fixes #558 

@jimthedev 644eb50 highlights the need for making the repo commitizen friendly. The remaining 2 commits are to bring related sections together. The rough outline now is 

 - Commitizen for project contributors
   * sub topics...
 - Commitizen for project maintainers
   * sub topics...
 - Non-code related topics 

The last 2 edits were not necessary strictly speaking but I think it helps in bringing a top-down flow of topics that belong together. 

E.g., after doing the local setup, one can read about the global setup. Next, once you're done with single projects, one may be interested in setting up multi-repo projects. "Adapters" seem the natural fit as a next topic. "Retrying failed commits" seemed like an update that came later with certain version & up so it is after Adapters.

Keeping up with this, we find that there are no more topics for "Commitizen for project contributors", so we start with "Commitizen for project maintainers". And then we talk about going further and other important topics.

The idea is easy skimming of the readme starting with the most important parts first and gradually taking the reader to advanced & deeper topics. 

Let me know your thoughts.

### CODE REVIEW

**Comment by jimthedev** [comment]
Hey @mrchief I can merge this now. Sorry for the delay. If you can just resolve the conflicts then I will press the button. Again thanks for the contribution.

- Jim

**Comment by mrchief** [comment]
I tried resolving using GitHub UI and I don't have high confidence in doing a correct merge. I need to dig deeper into this.

**Comment by mrchief** [comment]
@jimthedev Please check now and hit the button before it's too late again! 😄

**Comment by mrchief** [comment]
@jimthedev gentle reminder

**Pull request merged**
