### PR TITLE
Upgrade semantic-release

### PR DESCRIPTION
**Pull request by pvdlg**
I'm a maintainer of semantic-release and I noticed you are using a quite old version. The last version is `15.9.16`!

It seems you have a Travis job only for running semantic-release, but all your tests run on Azure Pipeline. semantic-release now works on pretty much any CI, so I removed the Travis config and added a new job on Azure Pipelines that runs semantic-release once all the test are successful.

In order to complete the config you should create 2 secured environment variable on Azure Pipeline:
- `GH_TOKEN` set with a [GitHub personal token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)
- `NPM_TOKEN` set with an [npm token](https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) (only the `auth-only` [level of npm two-factor authentication](https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported)

I never used Azure Pipeline before, so any review and feedback on my changes there would be much appreciated!

### CODE REVIEW

**Comment by pvdlg** [comment]
It should be fixed now!

**Comment by pvdlg** [comment]
Og I also noticed that the code coverage is not being uploaded anymore (it was in `.travis.yml` but Travis is not running anymore). I added it to the `azure-pipelines.yml`.

**Comment by pvdlg** [comment]
Actually I removed the code coverage as it fails with the error `unknown service. could not get configuration`. I guess the Codecov token must be added to environment variables.

**Comment by pvdlg** [comment]
I have error on Window for `npm test`. No idea why...it doesn't seems related to any change I made. Any idea of what cause the issue?

**Comment by pvdlg** [comment]
I can look at the issue with Windows. Can you describe quickly what the failing tests are doing?

**Comment by jimthedev** [comment]
I think the problem is that during an init we should not use configLoader but rather just blindly use the current directory. During commit however, we must walk up the tree to find the commit so it makes sense to use configLoader. This is just my assessment on first glance.

**Comment by pvdlg** [comment]
Is this problem happens because semantic-release itself uses `commitizen`? So adding a dependency that has a `config.commitizen.path` in it's `package.json` create the issue?


I noticed that `configLoader.load` in `init.js` accepts a `cwd` option but it's never passed (so it's always `process.cwd()` that is used). I don't really understand all the code to be honest...

I just wonder why just adding the semantic-release dependency in `devDependencies` create that issue. IF there is something we can do in semantic-release let me know.

**Comment by jimthedev** [comment]
Updated via renovatebot.

**Pull request closed without merging**
