### PR TITLE
fix(config loader): deal with config file charset

### PR DESCRIPTION
**Pull request by hxzhao527**
make sure that config file charset is utf-8, or throw detail to notify.
for #465 [Question] SyntaxError: Parsing JSON at for commitizen config failed

### CODE REVIEW

**Comment by hxzhao527** [comment]
I have resolve the conflict, maybe it is time to marge or close this issue.

**Comment by jimthedev** [comment]
Thanks for your contribution! This looks good!

**Comment by harryparkdotio** [comment]
@jimthedev can we revert this, or at least provide a hotfix release which includes `is-utf8` as a dependency?

**Comment by jimthedev** [comment]
@harryparkdotio Revert issued.

**Pull request merged**
