### PR TITLE
fix(cache): place commitizen.json in node_modules

### PR DESCRIPTION
**Pull request by kentcdodds**
The `AVA` project does this and I thought it was a great idea. No idea whether this change actually works, but I thought it'd be a better way to start a conversation about this than just an issue :-)

It just bothers me to have the `commitizen.json` in my root directory :-(

Worst case, could we change it to `.commitizen.json` so it's hidden in finder? :-)

### CODE REVIEW

**Comment by jimthedev** [comment]
Thanks @kentcdodds! This is a good starting point for discussion. I like to hear about how others are solving similar issues. We can certainly rename the file to hide it in finder. One concern I have in this method is, should blowing away node_modules really blow away your last commit message?

**Comment by kentcdodds** [comment]
Meh, I don't think that blowing away node_modules between a commit failure is a common case. In fact, reusing a commit isn't even a super common use case.

**Comment by pmcelhaney** [comment]
Yeah, I don't think losing the commit message is such a big deal. But here's another option. If you don't want the message clogging up your home directory and you *really* don't want to lose it, store it in git notes. 

https://git-scm.com/blog/2010/08/25/notes.html

**Comment by racer1988** [comment]
I agree with moving file in node_modules

**Comment by jimthedev** [comment]
@kentcdodds Thanks again for this. Just getting caught up on these PRs. This was actually resolved in thanks to @LinusU's fantastic [cachedir](https://github.com/linusu/node-cachedir) lib. You can safely delete ~/commitizen.json. https://github.com/commitizen/cz-cli/commit/27fb1ae8ee48fe8b03f81f43c1210bd7af850e07

**Pull request closed without merging**
