### PR TITLE
style: adhere to standard code style

### PR DESCRIPTION
**Pull request by TheDancingCode**
Remove eslint rule overrides and adapt code accordingly. This completes the conversion to standard style as intended in [#406](https://github.com/commitizen/cz-cli/pull/406#issue-99321863).

### CODE REVIEW

**Comment by LinusU** [comment]
I personally prefer to slowly adapt every part of the code that as we change it, that way diffs and history (e.g. `git blame`) still works as intended.

That is how we are currently handling it in [express](https://github.com/expressjs/express)

On the other hand, I don't feel too strongly about this so I'll let @jimthedev decide :)

**Comment by TheDancingCode** [comment]
In understand your reasoning, but I'm not sure you'll ever get rid of the exceptions then. It presupposes contributors somehow being aware that the extra rules in the ESLint config are temporary. They would have to disable them before linting, and then re-enable them before submitting a PR. Your repo's history shows that that doesn't happen: last year's code changes and additions don't adhere to the `standard` code style.

**Comment by LinusU** [comment]
Maybe we could use this lovely project?

https://github.com/okonet/lint-staged

**Comment by TheDancingCode** [comment]
Won't that make the git diffs and blame even more confusing? A commit changing a part of the code in a file would suddenly have all these other stylistic changes in the rest of the file, unrelated to the commit.

Making one big style commit with an appropriate title at least signals clearly that all the changes in that commit are style related, and if needed, one can easily look for the git blame before this one commit.

**Comment by LinusU** [comment]
The idea is not to fix the entire file as soon as you touch it, but rather just fix the line that you touch. This has worked very well in the express project.

That being said, I'm also open to just merging this...

**Comment by jimthedev** [comment]
Will not implement.

**Pull request closed without merging**
