### PR TITLE
Add linting using eslint

### PR DESCRIPTION
**Pull request by LinusU**
I have based the eslint config on [standard style](http://standardjs.com), and then disabled the rules that we where breaking. My plan is to enable them back one by one after this gets merged, as to not edit too much of the code base with one pr.

This pr also includes f7aceeb which I guess fixes our first bug that was caught by the linting 🌟 🙌

### CODE REVIEW

**Comment by LinusU** [comment]
ping @jimthedev, any idea why appveyor is failing?

```text
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

and

```text
Resolve-Path : Cannot find path 'C:\projects\cz-cli\test\artifacts\65fadf84-b742-4197-8b4f-6f2cd9b82963\4c1fa249-620b-4359-9552-3636a9332edf\enduser-app\node_modules\cz-jira-smart-commit\node_modules\inquirer\node_modules\cli-cur
sor\node_modules\restore-cursor\node_modules\exit-hook\package.json' because it does not exist.
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:207 char:18
+     $fullPath = (Resolve-Path $Path).Path
+                  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\cz-...ok\package.json:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
 
Push-AppveyorArtifactInternal : Cannot bind argument to parameter 'FullPath' because it is null.
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:209 char:42
+     Push-AppveyorArtifactInternal -FullPath $fullPath -FileName $File ...
+                                             ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Push-AppveyorArtifactInternal], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Appveyor.BuildAgent.Api.Utils.PushAppveyorArtifactInternalCmdlet
 
Resolve-Path : Cannot find path 'C:\projects\cz-cli\test\artifacts\65fadf84-b742-4197-8b4f-6f2cd9b82963\4c1fa249-620b-4359-9552-3636a9332edf\enduser-app\node_modules\cz-jira-smart-commit\node_modules\inquirer\node_modules\cli-cur
sor\node_modules\restore-cursor\node_modules\exit-hook\readme.md' because it does not exist.
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:207 char:18
+     $fullPath = (Resolve-Path $Path).Path
+                  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\cz-...-hook\readme.md:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
 
Push-AppveyorArtifactInternal : Cannot bind argument to parameter 'FullPath' because it is null.
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:209 char:42
+     Push-AppveyorArtifactInternal -FullPath $fullPath -FileName $File ...
+                                             ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Push-AppveyorArtifactInternal], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Appveyor.BuildAgent.Api.Utils.PushAppveyorArtifactInternalCmdlet
```

If you could quickly explain what this is for in the appveyor.yml file, that would be appreciated :)

```yml
on_finish:
  - ps: $root = Resolve-Path .\test\artifacts; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }

artifacts:
  - path: test/artifacts/**/*
    name: test artifacts
```

Also, are you 👍 or 👎 on eslint? :)

**Comment by jimthedev** [comment]
@LinusU Love this PR. BTW, happy holidays and thank you so much for all the hard work you do on Commitizen. You've been a huge asset. If I can be a reference or anything, let me know.

Yes I <3 eslint. I'm more a fan of semistandard since I <3 semicolons but I am sure I could make it work. I think appveyor is failing because we're using npm2 and not 3. Npm 3 flattens the folder structure but 2 doesn't. It means that eventually you run into this issue on windows. Basically it means we can't support npm2 anymore on windows since the dependency structure is too deep. Perhaps we should just drop npm2 support since npm3 has been around a long time. We could do this in Commitizen 3.0?

**Comment by LinusU** [comment]
Thank you! I love helping out <3

I'm still trying to figure out exactly how this all ties together. I'm thinking that since I've only added `devDependencies` it shouldn't affect the actual published product...

As I've understood it, we are releasing via Travis CI, so what are the artifacts from Appveyor used for?

**Comment by jimthedev** [comment]
Good question about those lines in appveyor.yml. Basically they let us keep the files created as a result of running the tests so that we can inspect the contents of the test artifacts, the git status of the repos,  etc. I removed those lines for now and master is now passing in both environments. If you merge master into your branch then your appveyor tests should pass. Eventually I'd like to make it so that we can turn on and off artifact collection by an environment variable in the Appveyor UI.

**Comment by jimthedev** [comment]
Sorry. Hit the wrong button on mobile.

**Pull request merged**
