### PR TITLE
chore: Drop support for Node.js <6.x

### PR DESCRIPTION
**Pull request by LinusU**
BREAKING CHANGE: Older versions of Node.js is no longer supported

Tried to go thru all of the breaking changes in sematic-release to get it up to date, hopefully I didn't miss anything 🙈

### CODE REVIEW

**Comment by jimthedev** [comment]
Very very excellent @LinusU

**Comment by LinusU** [comment]
Oh, I forgot to update appveyor 😄

**Comment by jimthedev** [comment]
Travis isn't loading why the build failed so I am restarting it blindly.

**Comment by jimthedev** [comment]
Woah now they are failing fast and the logs just contain `null`. hmm

**Comment by jimthedev** [comment]
ok things seem to be working differently now that I cleared the travis cache. No idea what what broken but [seems like](https://github.com/travis-ci/travis-ci/issues/10106) it is a common issue.

**Comment by LinusU** [comment]
Upgraded to Babel 7 and took advantage of `@babel/preset-env` to only transpile what is necessary for Node.js 6.x, the transpiled code looks much better 🙌 🚀 should hopefully speed up the code a little bit ☺️

**Comment by jimthedev** [comment]
Excellent. PR looks good to me so feel free to self-merge when ready or continue to bring in a bunch of dep updates into this PR.

**Comment by jimthedev** [comment]
It looks like perhaps commitizen is finding an adapter when the tests requires that one isn't configured. Perhaps our tests aren't getting cleaned up properly on windows and thus an adapter is being left in place?

**Comment by LinusU** [comment]
Yeah, I don't really see how that can be though 🤔 

The temp workspace should be located at `test/.tmp/enduser-app` and should be cleared at the beginning of the tests...

**Comment by jimthedev** [comment]
I was able to replicate it on my old ass windows machine. I haven't had a chance to work on it yet though because npm install took the better part of a day on this thing.

**Comment by jimthedev** [comment]
Ok I also added the azure builds because why the heck not. Let me know if you can get at them @LinusU. I can add you to the azure CI org. Nice to have cross OS builds in one place. https://dev.azure.com/commitizen/cz-cli/_build/results?buildId=7&view=logs

**Comment by jimthedev** [comment]
@LinusU, Good news! I have cz building on Azure DevOps on Ubuntu, Windows and OSX https://dev.azure.com/commitizen/cz-cli/_build/results?buildId=14&view=logs

Not sure what the semantic-release story looks like but at least we can have confidence in the builds. Next step would be to merge this into your modernize branch.

**Comment by LinusU** [comment]
Awesome 👏 

Should I just rebase on master?

**Comment by jimthedev** [comment]
Yeah!

**Comment by jimthedev** [comment]
I am trying to find out how to get azure to show up in branch checks. I guess we'll see what runs when you rebase.

**Comment by LinusU** [comment]
Rebased 🚀

**Comment by LinusU** [comment]
Awesome! Seems to be showing up!

I'll remove both Travis and Appveyor then?

**Comment by LinusU** [comment]
Hmm, forgot about semantic-release 😄 

Here is some inspiration, although it seems like they only have one build so they might not have to deal with that 🤔 

https://github.com/isomorphic-git/isomorphic-git/blob/c6c3f156e85bedaf1709d26ad8003eabb84de8fb/azure-pipelines.yml#L56-L63

**Comment by LinusU** [comment]
The build is failing with the same error as we got on Appveyor 😞

**Comment by jimthedev** [comment]
Ha! At least we can start to isolate the issue a bit since I had a known good build with master on Windows. We should probably keep travis for now I think since semantic-release will need it until we can figure out the release cycle on azure w/semantic release.

**Comment by jimthedev** [comment]
The good news is that resolving the adapter resolution issue should fix all other tests since nothing will really work without correct adapter resolution.

**Comment by jimthedev** [comment]
> > We should probably keep travis for now I think since semantic-release will need it until we can figure out the release cycle on azure w/semantic release.
> 
> Sounds good, by only having one job on Travis we can skip the `travis-deploy-once` dance also ☺️

Yes. Now we just need Azure-DevOps-deploy-once. I think they use the term Releases but haven't figured out much more than that.

**Comment by LinusU** [comment]
Do you think this is a good approach? 248752b

**Comment by jimthedev** [comment]
I do! One thing is that currently azure devops is just using whatever node version happens to be on the boxes. I think they have nvm but there's less visibility into that without building some sort of matrix of builds using various node version.

**Comment by jimthedev** [comment]
I think we need something like this perhaps in our pipeline to grab artifactors, then we'd have a release job that actually takes those artifacts and runs the semantic release command against them. Obviously we'd only need one of the build artifacts to actually deploy to npm / github releases.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts#yaml-snippet

**Comment by LinusU** [comment]
> One thing is that currently azure devops is just using whatever node version happens to be on the boxes. I think they have nvm but there's less visibility into that without building some sort of matrix of builds using various node version.

Ah, right, it would be very nice to test on all supported versions: 6, 8, and 10.

Great to see some progress on this, thanks for all the help! 👏

**Comment by jimthedev** [comment]
Just a quick heads up and update that I am using this PR as the starting point to find whatever regression we're seeing. I am using modernize-part-deux and dep-updates branches to go back and forth while doing updates and watching the builds closely. So far I am not seeing where the Windows regression is coming in but when I find it I will post an update here.

**Comment by jimthedev** [comment]
Ok merged to master, sadly no release due to a 401 with semantic-release. My guess is an expired token or something. Will try to dig in but this alone closed a bunch of PRs. :)

**Comment by jimthedev** [comment]
FYI. Fixed semantic-release by updating tokens and this branch was released via Travis & semantic-release. Still have not upgraded it to latest as I will have to probably investigate further why it introduces that windows regression. For now our release process is that tests run in basically the same way they always did except that Azure has the best broad coverage while Travis is still doing releases when merging into master. For now that just means we need to be careful with our merges into master until we can have releases done through Azure and then can retire Travis.

**Comment by jimthedev** [comment]
One more note. Currently commitizen init seems to have issues so I have opened #572

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. Looks like you've made great progress!

**Comment by jimthedev** [comment]
@kaylangan thanks for stopping by! We're probably hammering the services as we migrate over so thank you very much for the open source plan. It really is a great service. 

The only thing I can think of that is specific to the JavaScript community is that it would be helpful to understand why artifacts are separated out from builds. The key bring that in travis or other services you just throw semantic-release or npm publish into your yml file and then use things like travis-run-once or other tools to ensure that publish is only run once. 

Artifacts is actually a better implementation here (I think) since you will only cut one release and would only do it if your builds work on your entire matrix (OSs and Node versions). The challenge I will be addressing next is that I currently am getting warnings that no files were found that could be copied into artifacts. I think once that is fixed then I will be able to run semantic-release / npm publish as an actual release against the artifacts. That will be the panacea. :)

**Comment by jimthedev** [comment]
@kaylangan another thing that would be great is the ability to style the pipeline badges or add some text in place of Azure Pipelines. While it is good advertising and a fine default, sometime you want to have one badge for master and one badge for latest/develop and it is useful to be able to see the name of that branch on the badge itself. Not critical, but a nice to have that others currently offer.

**Comment by kaylangan** [comment]
> @kaylangan another thing that would be great is the ability to style the pipeline badges or add some text in place of Azure Pipelines. While it is good advertising and a fine default, sometime you want to have one badge for master and one badge for latest/develop and it is useful to be able to see the name of that branch on the badge itself. Not critical, but a nice to have that others currently offer.

You can use `label=` to specify other text. Even supports emojis!

**Comment by jimthedev** [comment]
> > @kaylangan another thing that would be great is the ability to style the pipeline badges or add some text in place of Azure Pipelines. While it is good advertising and a fine default, sometime you want to have one badge for master and one badge for latest/develop and it is useful to be able to see the name of that branch on the badge itself. Not critical, but a nice to have that others currently offer.
> 
> You can use `label=` to specify other text. Even supports emojis!


cheers

**Pull request merged**
