### PR TITLE
fix(adapter): looks for adapter relative to git root

### LINKED ISSUE #324: catch some error when i upgrade the version to 2.8.5
Just a non node project:

Error: Could not locate node_modules in your project's root directory. Did you forget to npm init or npm install?
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined

### PR DESCRIPTION
**Pull request by pmcelhaney**
instead of npm root, which may not exist

fixes #324

### CODE REVIEW

**Comment by adjohnson916** [comment]
Should consider pros & cons of ShellJS + `git rev-parse --show-toplevel` vs. finding closest parent with `.git` directory e.g. via https://www.npmjs.com/package/find-parent-dir.

**Comment by LinusU** [comment]
I don't like ShellJS at all and would love to get rid of it, but this is currently breaking for some of our users so I would like to get this landed as soon as possible. Pull request to refactor welcome :)

**Comment by LinusU** [comment]
Thanks for the quick response @pmcelhaney 🎉

**Comment by pmcelhaney** [comment]
I prefer asking git for the root path rather than looking for the .git directory because I don't know if there's some edge case in which searching for the .git directory doesn't work. For example, is it possible to create a file called .git in a subdirectory? Is it possible to configure git so the directory is called something other ".git"?

**Comment by LinusU** [comment]
That's true, would be nice to switch to e.g. [execa](https://npmjs.com/execa) so that it's not blocking but instead gives a promise. Should probably have clarified but the thing I don't like about ShellJS is the synchronous nature of it...

**Comment by pmcelhaney** [comment]
I'm thinking about creating a new npm module that can find the various root / home folders across all OSes. 

```js
var rootz = require('rootz');

var git = rootz.sync.git(),
     hg = rootz.sync.hg(),
    svn = rootz.sync.svn(),
    npm = rootz.sync.npmPackage(),
   home = rootz.sync.userHome(),
    ...

// non-blocking
   rootz.git().then(function (gitRootDirectory) {
      ...
   })
```

What do you think? Would that be useful?

**Comment by LinusU** [comment]
I personally like small focused packages ([some reading](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328)). Maybe make it multiple packages with one package that depends on the other if someone wants that.

Then we we could to:

```js
const gitRoot = require('rootz-git')

gitRoot().then(dir => {
  // ...
})
```

without having to add anything that isn't related to git to this package.

**Pull request merged**
