### PR TITLE
refactor(git): use execa to invoke git

### PR DESCRIPTION
**Pull request by LinusU**

### CODE REVIEW

**Comment by LinusU** [comment]
Oh shit, `execa` doesn't support Node.js 0.x...

I've been actually meaning to suggest this anyhow, but now it seems even more appropriate. How about dropping support for Node.js 0.12?

I think that there is a number of reasons in favour of this, first of all Node.js 0.12 is officially unsupported as of 2016-12-31. Also, I don't think that anyone that is using commitizen is actually using that old of a version, or doesn't have the ability to upgrade. As I have understood it, the majority of the still running Node.js 0.x versions are on servers that have been running it for ages; applications that works and that have no benefit of upgrading.

When people are developing locally, I think that they are running the latest Stable, or possibly the latest LTS, and this is where the commits will happen.

This should probably happen in a major version though 🤔 

Another very interesting thing that dropping 0.x would give would be the ability to stop using babel. I think that most of the language features that we are using are already supported natively in Node 4.x. The only exception that I can think of is `import`/`export`, but I personally don't mind using `require`/`exports`. I think that dropping babel would help speed up development, I got bit by it as recent as today, when I was trying out the binary and didn't realise that I hadn't run `npm run build`...

This is of course all up to you @jimthedev, please give me your thoughts and I'll proceed accordingly 👍

**Comment by jimthedev** [comment]
Let's do this all in 3.0 and drop Node 0.12 support.

**Comment by LinusU** [comment]
Awesome, shall I create a `v3.x` branch and start merging PRs there?

Is [this list](https://github.com/commitizen/cz-cli/milestone/3) up to date or do you want something more in? I'll also add dropping 0.12 to that list

**Comment by jimthedev** [comment]
Yep, that list should still be good. Add in 0.12 as well. 

We were thinking about requiring adapters to self import inquirer, do you think we should still do this? I was thinking we could at least provide a patched version of inquirer that writes a warning to stdout if the loaded adapter doesn't require inquirer. This would let adapter authors get PRs about the coming breaking API change. Although we could go make PRs for public adapters, private adapters need a cli based alert.

**Comment by LinusU** [comment]
Yes, I think making a version that prints a deprecation message is very good, no rush in removing it :)

**Comment by LinusU** [comment]
I think deprecating it in 3.x and removing in 4.x sounds good, that way we won't nag anyone that stays on 2.x. Thoughts?

also, merging this to the 3.x branch now, I'll start sending some more PRs shortly :)

**Comment by jimthedev** [comment]
Perfect!

**Pull request merged**
