### PR TITLE
fix(tests): fix test when there is a global configuration

### LINKED ISSUE #211: tests fails if I there is global configuration
``` sh
吽 cat ~/.czrc
{ "path": "cz-conventional-changelog" }
```

``` sh
  10 passing (54s)
  12 failing

  1) adapter resolves adapter paths:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  2) adapter gets adapter prompter functions:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  3) commit should commit simple messages:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  4) commit should commit message with quotes:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  5) commit should commit multiline messages:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  6) commit should allow to override options passed to gulp-git:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  7) init installs an adapter with --save-dev:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  8) init installs an adapter with --save:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  9) init errors on previously installed adapter:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  10) init succeeds if force is true:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  11) init installs an adapter without --save-exact:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
  12) init installs an adapter with --save-exact:
     Error: the string "A previous adapter is already configured. Use --force to override" was thrown, throw an Error :)
```

If I remove or rename `~/.czrc`, all the tests passes.

### PR DESCRIPTION
**Pull request by sarbbottam**
fixed #211

### CODE REVIEW

**Comment by sarbbottam** [comment]
@jimthedev could you take a look?

**Comment by jimthedev** [comment]
Hi @sarbbottam. My wife's father died so I am not going to be able to look at PRs or issues until at least next week. Just wanted to let you know.

**Comment by sarbbottam** [comment]
Sorry to hear that, may his soul rest in peace.

**Comment by sarbbottam** [comment]
@jimthedev please have a look when you get time.

**Comment by LinusU** [comment]
I think that this can be done in a more clean way, with just one line of code. How about adding this before the for-loop?

```js
// Do not load user specific config when running the tests
if (process.env.npm_lifecycle_event === 'test') return undefined
```

**Comment by jimthedev** [comment]
This was fixed with #405

**Pull request closed without merging**
