### PR TITLE
feat(init): add pnpm support

### LINKED ISSUE #858: commitizen init doesn't work with pnpm
I had run the ``commitizen init cz-conventional-changelog --save-dev --save-exact`` command as per README, but it doesn't work, see a copy and paste of the error from commitizen at the end.

Suggestion: when there exists a ``pnpm-lock.yaml`` file, use pnpm instead of npm.

Here's my workaround:

```sh
pnpm add -D -E cz-conventional-changelog
```

Then add this block to the package.json file:

```json
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  },
```

The ``cz`` command works as usual from this point.

Error from ``commitizen init cz-conventional-changelog --save-dev --save-exact``:

```
Attempting to initialize using the npm package cz-conventional-changelog
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".pnpm": name cannot start with a period

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunnz/.npm/_logs/2021-11-10T12_28_43_823Z-debug.log
Error: Command failed: npm install cz-conventional-changelog --save-dev
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name ".pnpm": name cannot start with a period

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunnz/.npm/_logs/2021-11-10T12_28_43_823Z-debug.log

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at init (/Users/sunnz/Library/pnpm/nodejs/16.11.1/pnpm-global/5/node_modules/.pnpm/commitizen@4.2.4/node_modules/commitizen/dist/commitizen/init.js:1017:28)
    at Object.bootstrap (/Users/sunnz/Library/pnpm/nodejs/16.11.1/pnpm-global/5/node_modules/.pnpm/commitizen@4.2.4/node_modules/commitizen/dist/cli/commitizen.js:34:30)
    at Object.<anonymous> (/Users/sunnz/Library/pnpm/nodejs/16.11.1/pnpm-global/5/node_modules/.pnpm/commitizen@4.2.4/node_modules/commitizen/bin/commitizen.js:2:38)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6e 70 6d 20 57 41 52 4e 20 6f 6c 64 20 6c 6f 63 6b 66 69 6c 65 20 0a 6e 70 6d 20 57 41 52 4e 20 6f 6c 64 20 6c 6f 63 6b 66 69 6c 65 20 54 68 65 20 70 ... 491 more bytes>
  ],
  pid: 55718,
  stdout: <Buffer >,
  stderr: <Buffer 6e 70 6d 20 57 41 52 4e 20 6f 6c 64 20 6c 6f 63 6b 66 69 6c 65 20 0a 6e 70 6d 20 57 41 52 4e 20 6f 6c 64 20 6c 6f 63 6b 66 69 6c 65 20 54 68 65 20 70 ... 491 more bytes>
}
```

### LINKED ISSUE #884: Initialization error
I use the follwing command
npx commitizen init cz-conventional-changelog --save-dev --save-exact
The following error occurred：
image

I need help！
Thank you so much

### PR DESCRIPTION
**Pull request by chenaski**
Added `--pnpm` option. For `pnpm` available `--save`, `--save-dev` and `--save-exact` options.

Resolves: #893, resolves #858, resolves #884.

### CODE REVIEW

**Comment by huzedong2015** [comment]
How much longer will it take?

**Comment by chenaski** [comment]
Are there any extra steps I should take?

**Comment by hellorayza** [comment]
Can anyone help?

**Comment by pulanski** [comment]
would love to see these changes added

**Comment by jiamianmao** [comment]
would love to see these changes added

**Comment by mattyaodoit** [comment]
Keen to get this merged and support `pnpm`

**Comment by enrique-ramirez** [comment]
Any news on this?

**Comment by chenaski** [comment]
Does anyone know how everything works in this repo?

**Comment by HubooDeclan** [comment]
Can we get this merged?

**Comment by AmmarArnt** [comment]
Would love this PR merged too. Is this repo maintained?

**Comment by Ruobei** [comment]
would love to see these changes added

**Comment by wangrongding** [comment]
Looking forward to this pr being merged. 👀

**Review by jimthedev — APPROVED** [review]

**Comment by jimthedev** [comment]
It released but the [tests are failing](https://dev.azure.com/commitizen/cz-cli/_build/results?buildId=2174&view=logs&j=9deecfdf-0881-507a-c982-fab489c810f6&t=a5eaf76f-574c-54d2-025d-96e44ae1cbcb&l=617). So 

1. Build should not allow this.
2. We may need to roll back or at least mark this as breaking and fix the tests.

**Comment by chenaski** [comment]
I don't think there are any breaking changes, it seems I just forgot to update azure pipeline. 
We need to add a [pnpm installation](https://dev.azure.com/commitizen/cz-cli/_build/results?buildId=2174&view=logs&j=9deecfdf-0881-507a-c982-fab489c810f6&t=a5eaf76f-574c-54d2-025d-96e44ae1cbcb&l=355) before running the tests.

**Comment by Jalever** [comment]
Great!

**Pull request merged**
