### PR TITLE
ci: lint commits via commitlint

### PR DESCRIPTION
**Pull request by marionebl**
* commit message checking via git hook
* commit message linting on CI #57 
* migrate from `ghooks` to `husky` #410

### CODE REVIEW

**Comment by marionebl** [comment]
I think the failing AppVeyor build is unrelated

**Comment by ockxdd** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by marionebl** [comment]
@jimthedev Could you have a look and comment if you are interested in this? Is there a way to reach the commitizen team via chat?

**Comment by marionebl** [comment]
Closing to keep my "Open PR" view useful

**Pull request closed without merging**
